%global debug_package %{nil}
%define _datadir /opt/45drives
%define _build_id_links none

Name: ::package_name::
Version: ::package_version::
Release: ::package_build_version::%{?dist}
Summary: ::package_description_short::
License: ::package_licence::
URL: ::package_url::
Source0: %{name}-%{version}.tar.gz
BuildArch: ::package_architecture_el::
Requires: ::package_dependencies_el::

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

%description
::package_title::
::package_description_long::

%prep
%setup -q

%build

%install
rm -rf %{buildroot}
make DESTDIR=%{buildroot} SERIAL_VERSION="%{version}-::package_build_version::" install


%postun
if [ $1 == 0 ];then
    rm -rf /opt/45drives/serial45d
    rm -f /usr/bin/serial45d
    rmdir /opt/45drives --ignore-fail-on-non-empty
fi

%files
%dir %{_datadir}/serial45d
%defattr(-,root,root,-)
%{_datadir}/serial45d/*
%{_bindir}/*

%changelog
* Thu Nov 16 2023 Mark Hooper <mhooper@45drives.com> 3.0.0-2
- updated name of chassis used for new NVME Stornado from 2UTM to F2
* Wed Oct 04 2023 Mark Hooper <mhooper@45drives.com> 3.0.0-1
- added the ability to serialize HomeLab-HL15 Servers
* Wed Jul 26 2023 Mark Hooper <mhooper@45drives.com> 2.0.1-4
- added 2UTM chassis size for new stornado
* Wed Jul 26 2023 Mark Hooper <mhooper@45drives.com> 2.0.1-3
- updated config file
* Mon Apr 03 2023 Mark Hooper <mhooper@45drives.com> 2.0.1-2
- Added a check for serial number format to ensure that automatic detection works
  on older units that had a different format
* Tue Mar 21 2023 Mark Hooper <mhooper@45drives.com> 2.0.1-1
- updated serial45d to be used in 45Drives production as the primary means of serialization
- when selecting a unique product, config file is checked before presenting options
  for selection
- 45Drives production specific functionality will be imported from seperate library
  if present on system
* Fri Mar 17 2023 Mark Hooper <mhooper@45drives.com> 2.0.0-2
- updated config file
* Fri Mar 17 2023 Mark Hooper <mhooper@45drives.com> 2.0.0-1
- updated serial45d for use by 45Drives Production
- production specific functions imported into serial45d if present
* Thu Jan 26 2023 Mark Hooper <mhooper@45drives.com> 1.2.0-1
- Added a contingency for missing Motherboard FRU data.
* Mon Dec 05 2022 Mark Hooper <mhooper@45drives.com> 1.1.0-6
- updated how system version detection is handled when cpu string doesn't have desired
  keywords
* Wed Sep 14 2022 Mark Hooper <mhooper@45drives.com> 1.1.0-5
- Added support for ASRockRack EPC621D8A motherboards
- Added the ability to serialize F8X units (naming convention subject to change)
- improved key error checking in serial45d script when accessing fru data read from
  board
* Tue Sep 13 2022 Mark Hooper <mhooper@45drives.com> 1.1.0-4
- improved key error checking in serial45d script when accessing fru data read from
  board
* Tue Aug 23 2022 Mark Hooper <mhooper@45drives.com> 1.1.0-3
- FRU data is now dynamically generated and backed up in both plaintext and binary
  format
- Supermicro boards will now be flashed with binary fru data generated by serial45d
  using the restore options in IPMICFG
- ASRockRack EPC621D8A motherboards have been verified
- updated 45drives-tools dependency to 2.1.0
* Tue Aug 23 2022 Mark Hooper <mhooper@45drives.com> 1.1.0-2
- FRU data is now dynamically generated and backed up in both plaintext and binary
  format
- Supermicro boards will now be flashed with binary fru data generated by serial45d
  using the restore options in IPMICFG
- ASRockRack EPC621D8A motherboards have been verified
* Mon Aug 22 2022 Mark Hooper <mhooper@45drives.com> 1.1.0-1
- FRU data is now written using ipmitool
- binary fru data is now generated using fru-tool, with automatic backups stored
- plaintext backups of ipmitool fru output are now automatically stored without prompting
  user for input
* Mon Aug 08 2022 Mark Hooper <mhooper@45drives.com> 1.0.3-1
- added fx series chassis sizes and product names for testing
* Mon Aug 08 2022 Mark Hooper <mhooper@45drives.com> 1.0.2-7
- added Stornado-2U-Turbo product name to config.txt
- updated motherboard entries in config.txt
* Thu Jul 21 2022 Mark Hooper <mhooper@45drives.com> 1.0.2-6
- updated config file to include Stornado-2U-Turbo as a valid product
* Wed May 04 2022 Mark Hooper <mhooper@45drives.com> 1.0.2-5
- updated config file to include more cpu strings
* Thu Apr 28 2022 Mark Hooper <mhooper@45drives.com> 1.0.2-4
- added the ability to serialize AV15 Destroyinators
* Wed Mar 02 2022 Mark Hooper <mhooper@45drives.com> 1.0.2-3
- changed minimum 45Drives-tools dependency for el7 and el8 packages
* Wed Feb 23 2022 Mark Hooper <mhooper@45drives.com> 1.0.2-2
- added the ability to serialize 2U Stornado servers
* Thu Feb 10 2022 Mark Hooper <mhooper@45drives.com> 1.0.2-1
- added options for 2U Stornado
* Wed Sep 15 2021 Mark Hooper <mhooper@45drives.com> 1.0.1-5
- added support for X11SPi-TF Motherboards
* Mon Aug 30 2021 Mark Hooper <mhooper@45drives.com> 1.0.1-4
- added 45drives-tools > 2.0.1 as a dependency
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.1-3
- updated welcome message
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.1-2
- second stable build of serial45d
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.1-1
- First stable release
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-13
- made version output in welcome message conditional
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-12
- updated serial version welcome text
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-11
- removed extra newline characters in backup files
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-10
- added skip dialogue
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-9
- fixed indentation
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-8
- removed build id links in .spec file
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-7
- removed build id links in .spec file
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-6
- added _datadir definition in .spec files
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-5
- updated copyright file
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-4
- updated the package dependencies in manifest
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-3
- added required entries to manifest for el7 packaging
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-2
- added el7 packaging
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 1.0.0-1
- first release of serial45d
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 0.1.0-4
- updated architecture
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 0.1.0-3
- updated .gitignore
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 0.1.0-2
- updated makefile
* Wed Aug 25 2021 Mark Hooper <mhooper@45drives.com> 0.1.0-1
- first build of serial45d